Осуществить циклический сдвиг элементов прямоугольной матрицы на n элементов вправо или вниз (в зависимости от введеленного режима), n может быть больше количества элементов в строке или столбце

In [24]:
import numpy as np

In [35]:
# Генерация матрицы
rows = np.random.randint(3, 10)
cols = np.random.randint(3, 10)
matrix = np.random.randint(low=1, high=10, size=(rows, cols))

n = int(input("Введите количество элементов для сдвига (n): "))  # Количество элементов для сдвига
mode = input("Выберите режим сбвига: right/down")  # Режим сдвига: 'right' - вправо, 'down' - вниз

Введите количество элементов для сдвига (n): 2
Выберите режим сбвига: right/downright


In [36]:
def cyclic_shift(matrix, n, mode):
    rows, cols = matrix.shape

    # Преобразование матрицы в одномерный массив
    flattened_matrix = matrix.flatten()

    # Циклический сдвиг элементов вправо
    if mode == 'right':
        shifted_matrix = np.roll(flattened_matrix, n)

    # Циклический сдвиг элементов вниз
    elif mode == 'down':
        shifted_matrix = np.roll(flattened_matrix, n * cols)

    # Преобразование одномерного массива обратно в матрицу
    shifted_matrix = shifted_matrix.reshape((rows, cols))

    return shifted_matrix

In [37]:
shifted_matrix = cyclic_shift(matrix, n, mode)

print("Исходная матрица:")
print(matrix)
print("\nСдвинутая матрица:")
print(shifted_matrix)

Исходная матрица:
[[8 6 2 8 1 7 8]
 [1 5 6 5 5 9 1]
 [3 7 4 9 8 6 1]
 [3 4 8 9 9 3 9]
 [2 3 2 3 6 6 5]
 [7 6 8 7 1 7 6]
 [9 6 4 3 2 9 9]
 [4 5 6 3 9 2 9]
 [8 3 9 8 8 8 8]]

Сдвинутая матрица:
[[8 8 8 6 2 8 1]
 [7 8 1 5 6 5 5]
 [9 1 3 7 4 9 8]
 [6 1 3 4 8 9 9]
 [3 9 2 3 2 3 6]
 [6 5 7 6 8 7 1]
 [7 6 9 6 4 3 2]
 [9 9 4 5 6 3 9]
 [2 9 8 3 9 8 8]]
